swagger: '2.0'
info:
  version: '1.0'
  title: "EDT/EDL APIs"
  description: >-
    The Electronic Data Transfer (EDT) and Electronic Dispatch Logging (EDL) APIs provides the means for the Market Participants to engage on the Balancing Mechanism to handle request sent by NGESO. The requests can be classified as:
    
      a) EDT. NGESO will send the Acceptance/Rejection to the Physical Notifications made by the Participant
      b) EDT. NGESO will accept a Bids & Offers made earlier by the Participant
      c) EDL. Receive instructions from NGESO to change the Participant´s position
      
    A party that wishes to participate in the Balancing Mechanism will need to implement this API following the instructions described in the "onboarding process".
    
  license:
    name: NGESO
    url: https://www.nationalgrideso.com/terms-and-conditions
host: wa.api.xx.com
basePath: /ngeso/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
tags:
  - name: Health
    description: API Health
  - name: EDT
    description: Electronic Data Transfer
  - name: EDL
    description: Electronic Dispatch Logging
paths:
  /health:
    get:
      tags:
        - Health
      summary: Checks the health of the connectivity and credentials
      responses:
        200:
          description: >-
                    The health API will be used to
                    
                    a) check the health of the connection between NG ESO and the BM Participant hosting the API 
                    
                    b) validate that the NGSO credentials are accepted by the BM Participant 
          schema:
              $ref: '#/definitions/Health'
          examples:
            application/json:
              - version: "1.0"
                timestamp: '2018-10-14T12:00:00.123Z'
        400:
          description: Feature Not Found
          schema:
              $ref: '#/definitions/Error'
        401:
          description: Unauthorized.
          schema:
              $ref: '#/definitions/Error'
          examples:
            application/json:
              - message: "Not Authorized"
                code: '401'
                detail: 'The Token has expired'
                datetime: '2018-10-14T12:00:00.123Z'
        500:
          description: Technical Error
          schema:
              $ref: '#/definitions/Error'

definitions:
  Health:
    title: Health
    type: object
    required:
      - version
      - timestamp
    properties:
      version:
        type: string
      timestamp:
        type: string
  Error:
    type: object
    required:
      - code
      - message
      - detail
      - datetime
    properties:
      message:
        type: string
        example: 'Error message'
      code:
        type: string
        example: 'Error code'
      detail:
        type: string
        example: 'Error detailed information'
      datetime:
        type: string
        example: '2018-10-14T12:00:00.123Z'