swagger: '2.0'
info:
  version: '1.0'
  title: "Wider Access Participant Health Check"
  description: >-
    The health API will be used to:
    
    a) check the health of the connection between NG ESO and the Wider Access Participant hosting the API 
    
    b) validate that the NGSO credentials are accepted by the Wider Access Participant 

    Please follow the "onboarding process" to get the proper Authorization to consume this API.
  license:
    name: NGESO
    url: https://www.nationalgrideso.com/terms-and-conditions
host: api.participant.com
basePath: /ngeso/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
tags:
  - name: Health
    description: API Health
paths:
  /health:
    get:
      tags:
        - Health
      summary: Checks the connectivity health and credentials
      produces:
      - application/json
      parameters:
      - name: "OSCGAppKeyHeader"
        in: "header"
        required: true
        type: "string"
        description: "API Key"
      - name: "OSCGOAuthBearer"
        in: "header"
        required: true
        type: "string"
        description: "OAuth2 Token"
      responses:
        200:
          description: Successful Response
          schema:
              $ref: '#/definitions/Health'
          examples:
            application/json:
              - version: '1.0'
                timestamp: '2018-10-14T12:00:00.123Z'
        404:
          description: Not Found
          schema:
              $ref: '#/definitions/Error'
          examples:
            application/json:
              - message: "Resource not found"
                code: '404'
                detail: 'Resource not found'
                datetime: '2018-10-14T12:00:00.123Z'
        401:
          description: Unauthorized.
          schema:
              $ref: '#/definitions/Error'
          examples:
            application/json:
              - message: "Not Authorized"
                code: '401'
                detail: 'The Token has expired'
                datetime: '2018-10-14T12:00:00.123Z'
        500:
          description: Internal Server Error
          schema:
              $ref: '#/definitions/Error'
          examples:
            application/json:
              - message: "Error message on the server side"
                code: '500'
                detail: 'Detailed error message'
                datetime: '2018-10-14T12:00:00.123Z'

definitions:
  Health:
    title: API Health
    type: object
    required:
      - version
      - timestamp
    properties:
      version:
        type: string
      timestamp:
        type: string
  Error:
    title: Error payload
    type: object
    required:
      - code
      - message
      - detail
      - timestamp
    properties:
      code:
        type: string
        example: 'Error code'
      message:
        type: string
        example: 'Error message'
      detail:
        type: string
        example: 'Error detailed information'
      timestamp:
        type: string
        example: '2018-10-14T12:00:00.123Z'