swagger: '2.0'
info:
  version: '1.0'
  title: NGESO Wider Access Submission
  description: >-
    ---

    # Overview


    The Submission API allows the Market Participants (MP) to submit Physical
    Notifications, Quiescent Physical Notifications, Bids & Offers, & Maximum
    Export/Import Limits, before the Balancing Mechanism Gate is closed. It is
    the principal mechanism by which participants in the existing Pool submit
    their offer data to NGESO.


    ---

    # Notification Time

    The System Time of the Host shall be in GMT and be kept referenced to a
    recognised global time base. It is this time, which shall determine gate
    closure for submissions. Each invocation successfully transferred to the
    Host will be deemed to be a submission. The notification time of this file
    and hence all data contained within it shall be deemed to be the point in
    time that the submission was made.


    ---

    # Submission Acknoledgment:

    The acknowledgement message will contain the notification time of the
    submission processed by BM. The notification time will use the standard Time
    format defined in the Convention paragraph.


    ---


    # Submission Acceptance:

    Acceptance are produced once a submission request has been validated in its
    entirety. The acceptance response will contain a list of all BMUs for which
    all submitted data has passed formatting, consistency and validation tests.
    The output will be in the form of a list, sorted alphanumerically by BMU
    name.


    ---

    # Submission Rejection:

    Submission rejection are also produced once a submission file has been
    validated in its entirety. Each record contained within a file is checked
    for formatting, validity and consistency. Should formatting prove incorrect
    the requestr will not proceed to validation and will be rejected at that
    stage. Thus a record that has invalid data and is also incorrectly formatted
    for the type of data will only have a message stating that it was rejected
    owing to a formatting error. The validity of the record will not be
    considered. Once a record has completed and passed formatting checks, it
    will be checked against each applicable validation and consistency rule. Any
    and all of these failures will be reported individually for each submitted
    record. Hence a single row that does not comply with multiple validation or
    consistency rules, will give rise to multiple error messages within a reject
    request.


    ---

    # Onboarding:

    Please follow the onborarding process to get the proper Authorization to
    consume this API.


    ---

    # Conventions:

    **timeFrom**=  CCYY-MM-DD hh:mm

    **timeTo**=  CCYY-MM-DD hh:mm

    **levelFrom**=  MW

    **levelTo**=  MW

    **offerPrice**=  £ / MWh

    **bidPrice**=  £ / MWh



    **Time Format:**

    **CCYY**= year (numeric)

    **MM**= month (numeric)

    **DD**= day (numeric)

    a single space separator between date and time

    **hh**= hours

    **mm**= minutes 
  license:
    name: NGESO
    url: 'https://www.nationalgrideso.com/terms-and-conditions'
host: api.wa.nationalgrid.com
basePath: /ngeso/v1
tags:
  - name: submission
    description: EDL Balancing Participants Submissions
    externalDocs:
      description: Find out more
      url: 'https://www.nationalgrideso.com/'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /submission:
    post:
      tags:
        - submission
      summary: 'Add a new submission [Market Participant -> NGESO]'
      consumes:
        - application/json
      parameters:
        - name: OSCGAppKeyHeader
          in: header
          required: true
          type: string
          description: API Key
        - name: OSCGOAuthBearer
          in: header
          required: true
          type: string
          description: OAuth2 Token
        - in: body
          name: submission
          description: Submission Request Data
          required: true
          schema:
            $ref: '#/definitions/Submission'
      responses:
        '200':
          description: Successful Response
          schema:
            type: object
            items:
              $ref: '#/definitions/Response'
          examples:
            application/json:
              - version: '1.0'
                timestamp: '2018-10-11T12:00:00.123Z'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              - message: Bad Request
                code: '400'
                detail: Wrong Data Format
                timestamp: '2018-10-11T12:00:00.123Z'
                version: '1.0'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              - message: Not Authorized
                code: '401'
                detail: The Token has expired
                timestamp: '2018-10-11T12:00:00.123Z'
                version: '1.0'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              - message: Resource not found
                code: '404'
                detail: Resource not found
                timestamp: '2018-10-11T12:00:00.123Z'
                version: '1.0'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              - message: Error message on the server side
                code: '500'
                detail: Detailed error message
                timestamp: '2018-10-11T12:00:00.123Z'
                version: '1.0'
definitions:
  Submission:
    title: Submission Request data
    type: object
    required:
      - sequence
      - agentName
      - BMUSubmissionElements
    properties:
      sequence:
        type: integer
        format: int32
        example: 12345
      agentName:
        type: string
        title: Agent Name
        example: TR_AGT
      BMUSubmissionElements:
        type: array
        items:
          $ref: '#/definitions/BMUSubmissionElements'
  BMUSubmissionElements:
    title: BMU Submission Element
    type: object
    required:
      - bmUnitName
    properties:
      bmUnitName:
        type: string
        title: Unit Name
        example: BM_UNIT_1
      pn:
        type: array
        items:
          $ref: '#/definitions/PN'
      qpn:
        type: array
        items:
          $ref: '#/definitions/QPN'
      bod:
        type: array
        items:
          $ref: '#/definitions/BOD'
      mel:
        type: array
        items:
          $ref: '#/definitions/MEL'
      mil:
        type: array
        items:
          $ref: '#/definitions/MIL'
  PN:
    title: Physical Notification
    type: object
    properties:
      timeFrom:
        type: string
        example: '2018-10-14 06:00'
      timeTo:
        type: string
        example: '2018-10-14 10:00'
      levelFrom:
        type: number
        example: 10
      levelTo:
        type: number
        example: 20
    required:
      - timeFrom
      - timeTo
      - levelFrom
      - levelTo
  QPN:
    title: Quiescent Physical Notification
    type: object
    properties:
      timeFrom:
        type: string
        example: '2018-10-14 06:00'
      timeTo:
        type: string
        example: '2018-10-14 10:00'
      levelFrom:
        type: number
        example: 15
      levelTo:
        type: number
        example: 25
    required:
      - timeFrom
      - timeTo
      - levelFrom
      - levelTo
  BOD:
    title: Bid-Offer Data
    type: object
    properties:
      timeFrom:
        type: string
        example: '2018-10-14 06:00'
      timeTo:
        type: string
        example: '2018-10-14 10:00'
      levelFrom:
        type: number
        example: 10
      levelTo:
        type: number
        example: 20
      pairNumber:
        type: number
        example: 123456
      offerPrice:
        type: number
        example: 12.31
      bidPrice:
        type: number
        example: 1.77
    required:
      - timeFrom
      - timeTo
      - levelFrom
      - levelTo
      - pairNumber
      - offerPrice
      - bidPrice
  MEL:
    title: Maximum Export Limit
    type: object
    properties:
      timeFrom:
        type: string
        example: '2018-10-14 06:00'
      timeTo:
        type: string
        example: '2018-10-14 10:00'
      maximumExportLevelFrom:
        type: number
        example: 1977
      maximumExportLevelTo:
        type: number
        example: 2010
    required:
      - timeFrom
      - timeTo
      - maximumExportLevelFrom
      - maximumExportLevelTo
  MIL:
    title: Maximum Import Limit
    type: object
    properties:
      timeFrom:
        type: string
        example: '2018-10-14 06:00'
      timeTo:
        type: string
        example: '2018-10-14 10:00'
      maximumImportLevelFrom:
        type: number
        example: 1977
      maximumImportLevelTo:
        type: number
        example: 2010
    required:
      - timeFrom
      - timeTo
      - maximumImportLevelFrom
      - maximumImportLevelTo
  Response:
    title: Successful Submission Response
    type: object
    properties:
      version:
        type: string
        example: '1.0'
      timestamp:
        type: string
        example: '2018-10-11T01:02:03.456Z'
    required:
      - version
      - timestamp
  Error:
    title: Error payload
    type: object
    required:
      - version
      - code
      - message
      - detail
      - timestamp
    properties:
      version:
        type: string
        example: '1.0'
      code:
        type: string
        example: '000'
      message:
        type: string
        example: Error message
      detail:
        type: string
        example: Error detailed information
      timestamp:
        type: string
        example: '2018-10-11T01:02:03.456Z'
